version: "3.9"

services:
  qradar-dashboard:
    image: qradar-dashboard:latest
    container_name: qradar-dashboard

    # Porta 9050 do host -> 9050 da aplicação no container
    # Porta 9001 do host -> 22 (SSH) no container
    ports:
      - "9000:9050"
      - "9001:22"

    # Persistência de arquivos importantes
    volumes:
      - /opt/qradar-dashboard/alerts_state.json:/opt/qradar-dashboard/alerts_state.json
      - /opt/qradar-dashboard/users.db:/opt/qradar-dashboard/users.db
      - /opt/qradar-dashboard/keys:/opt/qradar-dashboard/keys

    restart: unless-stopped
